version: "3.9"

services:
    db:
        image: mysql
        ports: 
            - 3307:3306
    crowdin:
        build: .
        depends_on:
            - db
        ports:
            - 8000:8000
        command: composer upgrade